services:
  - type: web
    name: dth-guid-demo-v2-bearer-dth
    env: docker
    autoDeploy: true
    dockerCommand: ["node", "apps/dth/server.js"]
    envVars:
      - key: PORT
        value: "10000"
      - key: APP_KIND
        value: "dth"
      - key: BASE_HOST
        fromService: { type: web, name: dth-guid-demo-v2-bearer-dth, property: host }
      - key: BENEFITS_HOST
        fromService: { type: web, name: dth-guid-demo-v2-bearer-dth, property: host }
      - key: KONG_HOST
        fromService: { type: web, name: dth-guid-demo-v2-bearer-dth, property: host }
      - key: ACCESS_HOST
        fromService: { type: web, name: dth-guid-demo-v2-bearer-dth, property: host }
      - key: DEMO_BEARER_TOKEN
        generateValue: true
      - key: REDIRECT_MODE
        value: "true"
    healthCheckPath: /health

  - type: web
    name: dth-guid-demo-v2-bearer-guid
    env: docker
    autoDeploy: true
    dockerCommand: ["node", "apps/guid/server.js"]
    envVars:
      - key: PORT
        value: "10001"
      - key: APP_KIND
        value: "guid"
      - key: BASE_HOST
        fromService: { type: web, name: dth-guid-demo-v2-bearer-guid, property: host }
      - key: DEMO_BEARER_TOKEN
        generateValue: true
    healthCheckPath: /health
